spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
#    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
#        hbm2ddl:
#          delimiter: ";"
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql